openapi: 3.0.0
info:
  title: E-commerce API
  description: API for managing customers, products, and orders.
  version: 1.0.0
servers:
  - url: http://localhost:8080/
    description: Local server

tags:
  - name: Authentication
    description: Authentication operations
  - name: Customers
    description: Operations related to customers
  - name: Products
    description: Operations related to products
  - name: Orders
    description: Operations related to orders
  
paths:
  /auth/login:
    post:
      summary: Generate Authentication Token
      operationId: generateToken
      tags:
        - Authentication
      responses:
        '200':
          description: Token generated successfully

  # Customer Endpoints
  /customers:
    get:
      summary: Get all customers
      operationId: getCustomers
      tags:
        - Customers
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of customers returned
    post:
      summary: Create a new customer
      operationId: createCustomer
      tags:
        - Customers
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                cpf:
                  type: string
      responses:
        '201':
          description: Customer created successfully

  /customers/{id}:
    get:
      summary: Get a specific customer
      operationId: getCustomer
      tags:
        - Customers
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Customer found
    put:
      summary: Update a customer
      operationId: updateCustomer
      tags:
        - Customers
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                cpf:
                  type: string
      responses:
        '200':
          description: Customer updated
    delete:
      summary: Delete a customer
      operationId: deleteCustomer
      tags:
        - Customers
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Customer deleted

  # Product Endpoints
  /products:
    get:
      summary: Get all products
      operationId: getProducts
      tags:
        - Products
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of products returned
    post:
      summary: Create a new product
      operationId: createProduct
      tags:
        - Products
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
      responses:
        '201':
          description: Product created successfully

  /products/{id}:
    get:
      summary: Get a specific product
      operationId: getProduct
      tags:
        - Products
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Product found
    put:
      summary: Update a product
      operationId: updateProduct
      tags:
        - Products
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: number
      responses:
        '200':
          description: Product updated
    delete:
      summary: Delete a product
      operationId: deleteProduct
      tags:
        - Products
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Product deleted

  # Order Endpoints
  /orders:
    get:
      summary: Get all orders
      operationId: getOrders
      tags:
        - Orders
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of orders returned
    post:
      summary: Create an order
      operationId: createOrder
      tags:
        - Orders
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_id:
                  type: integer
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      product_id:
                        type: integer
                      quantity:
                        type: integer
      responses:
        '201':
          description: Order created

  /orders/{id}:
    get:
      summary: Get a specific order
      operationId: getOrder
      tags:
        - Orders
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Order found
    put:
      summary: Update an order
      operationId: updateOrder
      tags:
        - Orders
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
      responses:
        '200':
          description: Order updated
    delete:
      summary: Delete an order
      operationId: deleteOrder
      tags:
        - Orders
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Order deleted

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
